spring.application.name=meeting-room
spring.datasource.url=jdbc:postgresql://localhost:5432/meeting_room_db
spring.datasource.username=meeting_user
spring.datasource.password=${POSTGRES_MEETING_DB}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true